spring:
  application:
    name: feign-hystrix-service
  profiles:
    active: pro
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/    
ribbon:
  eureka:
    enabled: true      #serviceList 交给eureka管理。ribbon就不要配置ServiceList了
    
            
# feign开启hystrix熔断服务
feign:
  hystrix:
    enabled: true

---
spring:
  profiles: dev
server:
  port: 81
    
---
spring:
  profiles: pro
server:
  port: 83