spring:
  profiles:
    active: dev
---
spring:
  application:
    name: cloud-server
  profiles: dev
server:
  port: 8761
eureka:
  instance:
    hostname: slave1
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka
    
---
spring:
  application:
    name: cloud-server
  profiles: pro
server:
  port: 8762
eureka:
  instance:
    hostname: slave2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka